from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1311, 1006)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 40, 851, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(28)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(800, 80, 591, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 130, 591, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 40, 551, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("resources/headIcon.png"))
        self.label_4.setObjectName("label_4")

        self.sender_text_field = QtWidgets.QTextEdit(self.centralwidget)
        self.sender_text_field.setEnabled(True)
        self.sender_text_field.setGeometry(QtCore.QRect(60, 500, 451, 441))
        self.sender_text_field.setReadOnly(True)
        self.sender_text_field.setObjectName("sender_text_field")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.start_communication_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_communication_button.setGeometry(QtCore.QRect(550, 660, 191, 71))
        self.start_communication_button.setObjectName("start_communication_button")


        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 440, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(890, 440, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.receiver_text_field = QtWidgets.QTextEdit(self.centralwidget)
        self.receiver_text_field.setGeometry(QtCore.QRect(780, 500, 451, 441))
        self.receiver_text_field.setReadOnly(True)
        self.receiver_text_field.setObjectName("receiver_text_field")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(820, 260, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.message_text_field = QtWidgets.QTextEdit(self.centralwidget)
        self.message_text_field.setGeometry(QtCore.QRect(780, 320, 451, 101))
        self.message_text_field.setObjectName("message_text_field")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(330, 260, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(600, 900, 91, 41))
        self.exit_button.setObjectName("exit_button")

        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(600, 790, 91, 41))
        self.clear_button.setObjectName("clear_button")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 330, 68, 58))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.COM1_port_check = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.COM1_port_check.setFont(font)
        self.COM1_port_check.setObjectName("COM1_port_check")
        self.verticalLayout.addWidget(self.COM1_port_check)

        self.COM2_port_check = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.COM2_port_check.setFont(font)
        self.COM2_port_check.setObjectName("COM2_port_check")
        self.verticalLayout.addWidget(self.COM2_port_check)

        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(360, 330, 254, 58))
        self.widget1.setObjectName("widget1")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.default_checksum_check = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.default_checksum_check.setFont(font)
        self.default_checksum_check.setObjectName("default_checksum_check")
        self.verticalLayout_2.addWidget(self.default_checksum_check)

        self.crc_checksum_check = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.crc_checksum_check.setFont(font)
        self.crc_checksum_check.setObjectName("crc_checksum_check")
        self.verticalLayout_2.addWidget(self.crc_checksum_check)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Telekomunikacja i przetwarzanie sygnałów"))
        self.label_2.setText(_translate("MainWindow", "Zadanie 2 - Protokół XMODEM"))
        self.label_3.setText(_translate("MainWindow", "Łukasz Janiszewski, Jakub Muszyński"))
        self.label_5.setText(_translate("MainWindow", "Wybierz port nadawcy:"))
        self.start_communication_button.setText(_translate("MainWindow", "Rozpocznij komunikację"))
        self.label_6.setText(_translate("MainWindow", "Logi portu nadawcy:"))
        self.label_7.setText(_translate("MainWindow", "Logi portu odbiorcy:"))
        self.label_8.setText(_translate("MainWindow", "Wpisz wiadomość, jaką chcesz przesłać:"))
        self.label_9.setText(_translate("MainWindow", "Wybierz algorytm sumy kontrolnej:"))
        self.exit_button.setText(_translate("MainWindow", "Wyjdź"))
        self.clear_button.setText(_translate("MainWindow", "Wyczyść"))
        self.COM1_port_check.setText(_translate("MainWindow", "COM1"))
        self.COM2_port_check.setText(_translate("MainWindow", "COM2"))
        self.default_checksum_check.setText(_translate("MainWindow", "Domyślny dla protokołu XMODEM"))
        self.crc_checksum_check.setText(_translate("MainWindow", "CRC16"))